services:
  postgres:
    image: postgres:16-alpine
    container_name: post-anki-dev-db
    environment:
      POSTGRES_USER: postanki
      POSTGRES_PASSWORD: postanki
      POSTGRES_DB: postanki_dev
    ports:
      - '5437:5432'
    volumes:
      - post-anki-dev-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postanki -d postanki_dev']
      interval: 2s
      timeout: 3s
      retries: 20

volumes:
  post-anki-dev-db-data:
