/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConcernsRouteImport } from './routes/concerns'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as AdminObservabilityRouteImport } from './routes/admin-observability'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProbeTopicIdRouteImport } from './routes/probe.$topicId'
import { Route as CurriculumCurriculumIdRouteImport } from './routes/curriculum.$curriculumId'
import { Route as ApiElectricShapeRouteImport } from './routes/api.electric-shape'
import { Route as ProbeTagTagIdRouteImport } from './routes/probe.tag.$tagId'
import { Route as CurriculumCurriculumIdStatsRouteImport } from './routes/curriculum.$curriculumId_.stats'
import { Route as CurriculumCurriculumIdAssessRouteImport } from './routes/curriculum.$curriculumId_.assess'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsRoute = ConcernsRouteImport.update({
  id: '/concerns',
  path: '/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminObservabilityRoute = AdminObservabilityRouteImport.update({
  id: '/admin-observability',
  path: '/admin-observability',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeTopicIdRoute = ProbeTopicIdRouteImport.update({
  id: '/probe/$topicId',
  path: '/probe/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCurriculumIdRoute = CurriculumCurriculumIdRouteImport.update({
  id: '/curriculum/$curriculumId',
  path: '/curriculum/$curriculumId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricShapeRoute = ApiElectricShapeRouteImport.update({
  id: '/api/electric-shape',
  path: '/api/electric-shape',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeTagTagIdRoute = ProbeTagTagIdRouteImport.update({
  id: '/probe/tag/$tagId',
  path: '/probe/tag/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCurriculumIdStatsRoute =
  CurriculumCurriculumIdStatsRouteImport.update({
    id: '/curriculum/$curriculumId_/stats',
    path: '/curriculum/$curriculumId/stats',
    getParentRoute: () => rootRouteImport,
  } as any)
const CurriculumCurriculumIdAssessRoute =
  CurriculumCurriculumIdAssessRouteImport.update({
    id: '/curriculum/$curriculumId_/assess',
    path: '/curriculum/$curriculumId/assess',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-observability': typeof AdminObservabilityRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/concerns': typeof ConcernsRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/today': typeof TodayRoute
  '/api/electric-shape': typeof ApiElectricShapeRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
  '/probe/$topicId': typeof ProbeTopicIdRoute
  '/curriculum/$curriculumId/assess': typeof CurriculumCurriculumIdAssessRoute
  '/curriculum/$curriculumId/stats': typeof CurriculumCurriculumIdStatsRoute
  '/probe/tag/$tagId': typeof ProbeTagTagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-observability': typeof AdminObservabilityRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/concerns': typeof ConcernsRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/today': typeof TodayRoute
  '/api/electric-shape': typeof ApiElectricShapeRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
  '/probe/$topicId': typeof ProbeTopicIdRoute
  '/curriculum/$curriculumId/assess': typeof CurriculumCurriculumIdAssessRoute
  '/curriculum/$curriculumId/stats': typeof CurriculumCurriculumIdStatsRoute
  '/probe/tag/$tagId': typeof ProbeTagTagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-observability': typeof AdminObservabilityRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/concerns': typeof ConcernsRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/today': typeof TodayRoute
  '/api/electric-shape': typeof ApiElectricShapeRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
  '/probe/$topicId': typeof ProbeTopicIdRoute
  '/curriculum/$curriculumId_/assess': typeof CurriculumCurriculumIdAssessRoute
  '/curriculum/$curriculumId_/stats': typeof CurriculumCurriculumIdStatsRoute
  '/probe/tag/$tagId': typeof ProbeTagTagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-observability'
    | '/admin-settings'
    | '/concerns'
    | '/dashboard'
    | '/decide'
    | '/today'
    | '/api/electric-shape'
    | '/curriculum/$curriculumId'
    | '/probe/$topicId'
    | '/curriculum/$curriculumId/assess'
    | '/curriculum/$curriculumId/stats'
    | '/probe/tag/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-observability'
    | '/admin-settings'
    | '/concerns'
    | '/dashboard'
    | '/decide'
    | '/today'
    | '/api/electric-shape'
    | '/curriculum/$curriculumId'
    | '/probe/$topicId'
    | '/curriculum/$curriculumId/assess'
    | '/curriculum/$curriculumId/stats'
    | '/probe/tag/$tagId'
  id:
    | '__root__'
    | '/'
    | '/admin-observability'
    | '/admin-settings'
    | '/concerns'
    | '/dashboard'
    | '/decide'
    | '/today'
    | '/api/electric-shape'
    | '/curriculum/$curriculumId'
    | '/probe/$topicId'
    | '/curriculum/$curriculumId_/assess'
    | '/curriculum/$curriculumId_/stats'
    | '/probe/tag/$tagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminObservabilityRoute: typeof AdminObservabilityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ConcernsRoute: typeof ConcernsRoute
  DashboardRoute: typeof DashboardRoute
  DecideRoute: typeof DecideRoute
  TodayRoute: typeof TodayRoute
  ApiElectricShapeRoute: typeof ApiElectricShapeRoute
  CurriculumCurriculumIdRoute: typeof CurriculumCurriculumIdRoute
  ProbeTopicIdRoute: typeof ProbeTopicIdRoute
  CurriculumCurriculumIdAssessRoute: typeof CurriculumCurriculumIdAssessRoute
  CurriculumCurriculumIdStatsRoute: typeof CurriculumCurriculumIdStatsRoute
  ProbeTagTagIdRoute: typeof ProbeTagTagIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns': {
      id: '/concerns'
      path: '/concerns'
      fullPath: '/concerns'
      preLoaderRoute: typeof ConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-observability': {
      id: '/admin-observability'
      path: '/admin-observability'
      fullPath: '/admin-observability'
      preLoaderRoute: typeof AdminObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/$topicId': {
      id: '/probe/$topicId'
      path: '/probe/$topicId'
      fullPath: '/probe/$topicId'
      preLoaderRoute: typeof ProbeTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$curriculumId': {
      id: '/curriculum/$curriculumId'
      path: '/curriculum/$curriculumId'
      fullPath: '/curriculum/$curriculumId'
      preLoaderRoute: typeof CurriculumCurriculumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric-shape': {
      id: '/api/electric-shape'
      path: '/api/electric-shape'
      fullPath: '/api/electric-shape'
      preLoaderRoute: typeof ApiElectricShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/probe/tag/$tagId': {
      id: '/probe/tag/$tagId'
      path: '/probe/tag/$tagId'
      fullPath: '/probe/tag/$tagId'
      preLoaderRoute: typeof ProbeTagTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$curriculumId_/stats': {
      id: '/curriculum/$curriculumId_/stats'
      path: '/curriculum/$curriculumId/stats'
      fullPath: '/curriculum/$curriculumId/stats'
      preLoaderRoute: typeof CurriculumCurriculumIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$curriculumId_/assess': {
      id: '/curriculum/$curriculumId_/assess'
      path: '/curriculum/$curriculumId/assess'
      fullPath: '/curriculum/$curriculumId/assess'
      preLoaderRoute: typeof CurriculumCurriculumIdAssessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminObservabilityRoute: AdminObservabilityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ConcernsRoute: ConcernsRoute,
  DashboardRoute: DashboardRoute,
  DecideRoute: DecideRoute,
  TodayRoute: TodayRoute,
  ApiElectricShapeRoute: ApiElectricShapeRoute,
  CurriculumCurriculumIdRoute: CurriculumCurriculumIdRoute,
  ProbeTopicIdRoute: ProbeTopicIdRoute,
  CurriculumCurriculumIdAssessRoute: CurriculumCurriculumIdAssessRoute,
  CurriculumCurriculumIdStatsRoute: CurriculumCurriculumIdStatsRoute,
  ProbeTagTagIdRoute: ProbeTagTagIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
