/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConcernsRouteImport } from './routes/concerns'
import { Route as AdminSettingsRouteImport } from './routes/admin-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurriculumCurriculumIdRouteImport } from './routes/curriculum.$curriculumId'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsRoute = ConcernsRouteImport.update({
  id: '/concerns',
  path: '/concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCurriculumIdRoute = CurriculumCurriculumIdRouteImport.update({
  id: '/curriculum/$curriculumId',
  path: '/curriculum/$curriculumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/concerns': typeof ConcernsRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/today': typeof TodayRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/concerns': typeof ConcernsRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/today': typeof TodayRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-settings': typeof AdminSettingsRoute
  '/concerns': typeof ConcernsRoute
  '/dashboard': typeof DashboardRoute
  '/decide': typeof DecideRoute
  '/today': typeof TodayRoute
  '/curriculum/$curriculumId': typeof CurriculumCurriculumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-settings'
    | '/concerns'
    | '/dashboard'
    | '/decide'
    | '/today'
    | '/curriculum/$curriculumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-settings'
    | '/concerns'
    | '/dashboard'
    | '/decide'
    | '/today'
    | '/curriculum/$curriculumId'
  id:
    | '__root__'
    | '/'
    | '/admin-settings'
    | '/concerns'
    | '/dashboard'
    | '/decide'
    | '/today'
    | '/curriculum/$curriculumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ConcernsRoute: typeof ConcernsRoute
  DashboardRoute: typeof DashboardRoute
  DecideRoute: typeof DecideRoute
  TodayRoute: typeof TodayRoute
  CurriculumCurriculumIdRoute: typeof CurriculumCurriculumIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns': {
      id: '/concerns'
      path: '/concerns'
      fullPath: '/concerns'
      preLoaderRoute: typeof ConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-settings': {
      id: '/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$curriculumId': {
      id: '/curriculum/$curriculumId'
      path: '/curriculum/$curriculumId'
      fullPath: '/curriculum/$curriculumId'
      preLoaderRoute: typeof CurriculumCurriculumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ConcernsRoute: ConcernsRoute,
  DashboardRoute: DashboardRoute,
  DecideRoute: DecideRoute,
  TodayRoute: TodayRoute,
  CurriculumCurriculumIdRoute: CurriculumCurriculumIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
