export const LIVENESS_MIN_SCORE = 1;

export const LIVENESS_MAX_SCORE = 10;

export const LIVENESS_STARTING_SCORE = 7;

export const LIVENESS_DECAY_HALF_LIFE_DAYS = 10;

export const LIVENESS_GENERATION_THRESHOLD = 5;

export const LIVENESS_NUDGE_THRESHOLD = 4;

export const LIVENESS_NUDGE_COOLDOWN_DAYS = 7;

export const LIVENESS_REVIVAL_FLOOR = LIVENESS_GENERATION_THRESHOLD + 1;

export const LIVENESS_DAY_MS = 24 * 60 * 60 * 1000;
