import type { RouteName } from "./router.js";

export interface RouteDef {
  method: string;
  pattern: string | RegExp;
  name: RouteName;
  param?: string;
  params?: string[];
}

export const ROUTES: RouteDef[] = [
  { method: "GET", pattern: "/subjects", name: "listSubjects" },
  { method: "POST", pattern: "/subjects", name: "createSubject" },
  { method: "DELETE", pattern: /^\/subjects\/([^/]+)$/, name: "deleteSubject", param: "id" },
  { method: "POST", pattern: /^\/subjects\/([^/]+)\/merge$/, name: "mergeSubjects", param: "id" },
  { method: "GET", pattern: "/curricula", name: "listCurricula" },
  { method: "POST", pattern: "/curricula", name: "createCurriculum" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/merge$/, name: "mergeCurricula", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/move$/, name: "moveCurriculum", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/confirm$/, name: "confirmCurriculum", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/complete-pre-assessment$/, name: "completePreAssessment", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/sources$/, name: "addSources", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/reparse$/, name: "reparse", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/retry-research$/, name: "retryResearch", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/retry-structure-draft$/, name: "retryDraftStructure", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/approve-sources$/, name: "approveSources", param: "id" },
  { method: "GET", pattern: /^\/curricula\/([^/]+)\/structure-turns$/, name: "getStructureTurns", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/structure-turns$/, name: "submitStructureTurn", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/resolve-research-candidates$/, name: "resolveSupplementalResearch", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/confirm-structure$/, name: "confirmStructure", param: "id" },
  { method: "DELETE", pattern: /^\/sources\/([^/]+)$/, name: "deleteSource", param: "id" },
  { method: "GET", pattern: "/sources", name: "listLibrarySources" },
  {
    method: "POST",
    pattern: /^\/sources\/([^/]+)\/refetch$/,
    name: "refetchSource",
    param: "id",
  },
  { method: "POST", pattern: "/source-duplicate-scans", name: "triggerSourceDuplicateScan" },
  {
    method: "GET",
    pattern: "/source-duplicate-suggestions",
    name: "listSourceDuplicateSuggestions",
  },
  {
    method: "PATCH",
    pattern: /^\/source-duplicate-suggestions\/([^/]+)$/,
    name: "resolveSourceDuplicateSuggestion",
    param: "id",
  },
  { method: "PATCH", pattern: /^\/curricula\/([^/]+)\/modules\/order$/, name: "reorderModules", param: "id" },
  { method: "POST", pattern: /^\/curricula\/([^/]+)\/modules$/, name: "createModule", param: "id" },
  { method: "GET", pattern: /^\/curricula\/([^/]+)$/, name: "getCurriculum", param: "id" },
  { method: "PATCH", pattern: /^\/curricula\/([^/]+)$/, name: "updateCurriculum", param: "id" },
  { method: "DELETE", pattern: /^\/curricula\/([^/]+)$/, name: "deleteCurriculum", param: "id" },
  { method: "PATCH", pattern: /^\/modules\/([^/]+)\/topics\/order$/, name: "reorderTopics", param: "id" },
  { method: "POST", pattern: /^\/modules\/([^/]+)\/topics$/, name: "createTopic", param: "id" },
  { method: "PATCH", pattern: /^\/modules\/([^/]+)$/, name: "updateModule", param: "id" },
  { method: "DELETE", pattern: /^\/modules\/([^/]+)$/, name: "deleteModule", param: "id" },
  { method: "POST", pattern: /^\/modules\/([^/]+)\/comments$/, name: "addModuleComment", param: "id" },
  { method: "GET", pattern: /^\/topics\/([^/]+)\/gaps$/, name: "listTopicGaps", param: "id" },
  { method: "POST", pattern: /^\/topics\/([^/]+)\/comments$/, name: "addTopicComment", param: "id" },
  { method: "POST", pattern: /^\/topics\/([^/]+)\/probe\/answer$/, name: "submitProbe", param: "id" },
  { method: "POST", pattern: /^\/topics\/([^/]+)\/probe$/, name: "startProbe", param: "id" },
  { method: "GET", pattern: "/probe-sessions/active", name: "activeProbeSession" },
  { method: "POST", pattern: "/probe-sessions", name: "prepareProbeSession" },
  { method: "POST", pattern: /^\/probe-sessions\/([^/]+)\/answer$/, name: "answerProbeSession", param: "id" },
  { method: "POST", pattern: "/socratic-sessions", name: "startSocratic" },
  { method: "POST", pattern: /^\/socratic-sessions\/([^/]+)\/answer$/, name: "answerSocratic", param: "id" },
  { method: "PATCH", pattern: /^\/topics\/([^/]+)$/, name: "updateTopic", param: "id" },
  { method: "DELETE", pattern: /^\/topics\/([^/]+)$/, name: "deleteTopic", param: "id" },
  { method: "POST", pattern: "/gaps", name: "declareGap" },
  { method: "GET", pattern: "/gaps/due-for-resurface", name: "listGapsDueForResurface" },
  { method: "POST", pattern: /^\/gaps\/([^/]+)\/triage$/, name: "triageGap", param: "id" },
  {
    method: "POST",
    pattern: /^\/gaps\/([^/]+)\/mark-resurfaced$/,
    name: "markGapResurfaced",
    param: "id",
  },
  { method: "PATCH", pattern: /^\/gaps\/([^/]+)$/, name: "curateGap", param: "id" },
  { method: "GET", pattern: "/daily-push", name: "dailyPush" },
  { method: "POST", pattern: "/decide-sessions", name: "createDecideSession" },
  { method: "GET", pattern: "/decide-sessions", name: "listDecideSessions" },
  {
    method: "PATCH",
    pattern: /^\/decide-blind-spots\/([^/]+)$/,
    name: "resolveDecideBlindSpot",
    param: "id",
  },
  { method: "GET", pattern: "/cross-cutting", name: "crossCutting" },
  {
    method: "GET",
    pattern: "/gap-mastery/cross-cutting-nudge",
    name: "gapMasteryCrossCuttingNudge",
  },
  { method: "GET", pattern: "/admin/settings", name: "getAdminSettings" },
  { method: "PATCH", pattern: "/admin/settings", name: "updateAdminSettings" },
  { method: "GET", pattern: "/admin/observability", name: "getAdminObservability" },
  {
    method: "POST",
    pattern: /^\/probe-session-questions\/([^/]+)\/feedback$/,
    name: "submitProbeQuestionFeedback",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/socratic-turns\/([^/]+)\/feedback$/,
    name: "submitSocraticTurnFeedback",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/probe-session-questions\/([^/]+)\/open-questions$/,
    name: "captureProbeQuestionOpenQuestion",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/socratic-turns\/([^/]+)\/open-questions$/,
    name: "captureSocraticTurnOpenQuestion",
    param: "id",
  },
  { method: "GET", pattern: "/open-questions", name: "listOpenQuestions" },
  {
    method: "PATCH",
    pattern: /^\/open-questions\/([^/]+)$/,
    name: "resolveOpenQuestion",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/topics\/([^/]+)\/study-chat$/,
    name: "askStudyChat",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/curricula\/([^/]+)\/stats$/,
    name: "getCurriculumStats",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/curricula\/([^/]+)\/stats\/recommendations$/,
    name: "generateRecommendations",
    param: "id",
  },
  { method: "GET", pattern: "/streak", name: "getStreak" },
  { method: "GET", pattern: "/electric/v1/shape", name: "getElectricShape" },
  { method: "GET", pattern: "/tags", name: "listTags" },
  { method: "POST", pattern: "/tags", name: "createTag" },
  {
    method: "POST",
    pattern: /^\/tags\/([^/]+)\/assignments$/,
    name: "assignTag",
    param: "id",
  },
  {
    method: "DELETE",
    pattern: /^\/tags\/([^/]+)\/assignments\/([^/]+)$/,
    name: "removeTagAssignment",
    params: ["id", "assignmentId"],
  },
  { method: "POST", pattern: /^\/tags\/([^/]+)\/merge$/, name: "mergeTags", param: "id" },
  {
    method: "POST",
    pattern: /^\/topics\/([^/]+)\/lecture\/sources$/,
    name: "gatherLectureSources",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/topics\/([^/]+)\/lecture\/sources$/,
    name: "listLectureSourceCandidates",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/lecture-source-candidates\/([^/]+)$/,
    name: "reviewLectureSourceCandidate",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/topics\/([^/]+)\/lecture$/,
    name: "compileLecture",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/topics\/([^/]+)\/lecture$/,
    name: "getLecture",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/topics\/([^/]+)\/cards$/,
    name: "compileCards",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/topics\/([^/]+)\/cards$/,
    name: "getCards",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/subjects\/([^/]+)\/practice-settings$/,
    name: "getPracticeSettings",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/subjects\/([^/]+)\/practice-settings$/,
    name: "updatePracticeSettings",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/subjects\/([^/]+)\/phrase-batches$/,
    name: "createPhraseBatch",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/subjects\/([^/]+)\/attempts$/,
    name: "createAttempts",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/subjects\/([^/]+)\/phrase-bank$/,
    name: "getPhraseBank",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/subjects\/([^/]+)\/writing-checks$/,
    name: "createWritingCheck",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/subjects\/([^/]+)\/writing-checks$/,
    name: "listWritingChecks",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/subjects\/([^/]+)\/domain-map$/,
    name: "getDomainMap",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/domain-nodes\/([^/]+)$/,
    name: "updateDomainNode",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/domain-nodes\/([^/]+)\/merge$/,
    name: "mergeDomainNodes",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/subjects\/([^/]+)\/domain-priority-reviews$/,
    name: "triggerDomainPriorityReview",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/subjects\/([^/]+)\/domain-priority-suggestions$/,
    name: "listPrioritySuggestions",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/domain-priority-suggestions\/([^/]+)$/,
    name: "resolvePrioritySuggestion",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/subjects\/([^/]+)\/domain-priority-review-status$/,
    name: "getDomainPriorityReviewStatus",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/subjects\/([^/]+)\/doc-scans$/,
    name: "triggerDocScan",
    param: "id",
  },
  { method: "POST", pattern: "/doc-scans", name: "triggerAllDocScans" },
  {
    method: "GET",
    pattern: /^\/subjects\/([^/]+)\/doc-scan-suggestions$/,
    name: "listDocScanSuggestions",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/domain-topic-suggestions\/([^/]+)$/,
    name: "resolveDomainTopicSuggestion",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/domain-supersession-suggestions\/([^/]+)$/,
    name: "resolveDomainSupersessionSuggestion",
    param: "id",
  },
  { method: "POST", pattern: "/subject-duplicate-scans", name: "triggerSubjectDuplicateScan" },
  {
    method: "GET",
    pattern: "/subject-duplicate-suggestions",
    name: "listSubjectDuplicateSuggestions",
  },
  {
    method: "PATCH",
    pattern: /^\/subject-duplicate-suggestions\/([^/]+)$/,
    name: "resolveSubjectDuplicateSuggestion",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/curricula\/([^/]+)\/domain-mappings$/,
    name: "triggerCurriculumDomainMapping",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/curricula\/([^/]+)\/domain-mappings$/,
    name: "listCurriculumDomainMappings",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/curriculum-domain-mappings\/([^/]+)$/,
    name: "resolveCurriculumDomainMapping",
    param: "id",
  },
  { method: "POST", pattern: "/nudge-responses", name: "createNudgeResponse" },
  { method: "POST", pattern: "/learning-list-items", name: "captureLearningListItem" },
  { method: "GET", pattern: "/learning-list-items", name: "listLearningListItems" },
  {
    method: "PATCH",
    pattern: /^\/learning-list-items\/([^/]+)\/recommendation$/,
    name: "resolveLearningListRecommendation",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/learning-list-items\/([^/]+)\/destination$/,
    name: "chooseLearningListDestination",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/learning-list-items\/([^/]+)\/classification$/,
    name: "classifyLearningListItem",
    param: "id",
  },
  {
    method: "POST",
    pattern: /^\/learning-list-items\/([^/]+)\/nudge-responses$/,
    name: "createLearningListNudgeResponse",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/learning-list-items\/([^/]+)$/,
    name: "getLearningListItem",
    param: "id",
  },
  { method: "GET", pattern: "/role-templates", name: "listRoleTemplates" },
  { method: "POST", pattern: "/learning-paths", name: "createLearningPath" },
  { method: "GET", pattern: "/learning-paths", name: "listLearningPaths" },
  {
    method: "GET",
    pattern: /^\/learning-paths\/([^/]+)\/steps\/([^/]+)\/push$/,
    name: "getLearningPathStepPush",
    params: ["id", "stepId"],
  },
  {
    method: "GET",
    pattern: /^\/learning-paths\/([^/]+)$/,
    name: "getLearningPath",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/learning-paths\/([^/]+)$/,
    name: "updateLearningPath",
    param: "id",
  },
  { method: "POST", pattern: "/notes", name: "captureNote" },
  { method: "GET", pattern: "/notes/search", name: "searchNotes" },
  { method: "GET", pattern: "/notes/review", name: "reviewNote" },
  { method: "GET", pattern: "/notes", name: "listNotesForNode" },
  { method: "GET", pattern: "/analytics/coverage", name: "getCoverageReport" },
  { method: "GET", pattern: "/analytics/retention", name: "getRetentionReport" },
  { method: "GET", pattern: "/analytics/digest", name: "getWeeklyDigest" },
  { method: "GET", pattern: "/milestones", name: "listMilestones" },
  {
    method: "POST",
    pattern: /^\/topics\/([^/]+)\/study-materials$/,
    name: "requestStudyMaterial",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/topics\/([^/]+)\/study-materials$/,
    name: "listStudyMaterials",
    param: "id",
  },
  { method: "POST", pattern: "/study-sessions", name: "createStudySession" },
  { method: "GET", pattern: "/study-sessions/consistency", name: "getStudySessionConsistency" },
  { method: "GET", pattern: "/study-sessions", name: "listStudySessions" },
  {
    method: "GET",
    pattern: /^\/study-sessions\/([^/]+)\/push$/,
    name: "getStudySessionPush",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/study-sessions\/([^/]+)\/start$/,
    name: "startStudySession",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/study-sessions\/([^/]+)\/end$/,
    name: "endStudySession",
    param: "id",
  },
  {
    method: "PATCH",
    pattern: /^\/study-sessions\/([^/]+)\/answers$/,
    name: "recordStudySessionAnswer",
    param: "id",
  },
  {
    method: "GET",
    pattern: /^\/study-sessions\/([^/]+)$/,
    name: "getStudySession",
    param: "id",
  },
];
